### ISSUE TITLE
Error when running static video with video_stream_opencv

### ISSUE THREAD

**Issue by Rhenry1995** [RViMLab/vrviz#7]
Getting the following error when playing a static video with no pose requirements. 

```[ERROR] [1549975542.140186209]: "vrviz_intermediate" passed to lookupTransform argument target_frame does not exist. 
================================================================================REQUIRED process [vrviz-4] has died!
process has died [pid 16904, exit code -11, cmd /home/ros/.steam/steam/ubuntu12_32/steam-runtime/run.sh /home/ros/github/vrviz/devel/lib/vrviz/vrviz_gl -novblank /markers:=/markers /cloud:=/cloud /controller_twist:=/controller_twist __name:=vrviz __log:=/home/ros/.ros/log/19ccdc6e-2ec4-11e9-98f8-001fbc129174/vrviz-4.log].
log file: /home/ros/.ros/log/19ccdc6e-2ec4-11e9-98f8-001fbc129174/vrviz-4*.log
Initiating shutdown!
================================================================================
```

**Comment by john-j-oneill** [comment]
I figured out the problem and I'm pretty sure I fixed it. In case you were wondering, the issue was that at some point I changed to using 2 threads, one for VR and one for ROS messages, and I had never updated the image code to account for that, so the ROS thread was doing GL calls, which made it freak out. It should be fixed now, but let me know if it isn't.

**Comment by cbergeles** [comment]
Thanks John :) Fingers crossed - we will send you the first video of the
integrated visualisation system ever captured!

**Comment by john-j-oneill** [comment]
I'm going to close this issue due to email conversation with @Rhenry1995 that I believe fully resolved it. 

As a note from our email, there is now a `manual_image_copy` option (added here: f867aebf50f9194842fbfd7e17b7556206546efc) which tries to combine the flip (due to CV/GL differences) and the BGR->RGBA conversion (OpenVR wants alpha, since this is technically an overlay), and the thread copy, all into one manual function. This of course only works with BGR images, and while it's noticeably faster it does give a "rolling shutter" type effect, which may be noticeable depending on the amount of motion in the scene. For anything less than SBS 1080p the normal mode should work just fine, but with 3840x1080 the normal mode runs at ~8Hz, and the `manual_image_copy` mode can improve that to ~22Hz.
